spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fedelico431@gmail.com
# Usa la nueva contrase\u00F1a que generaste
spring.mail.password=lsycdyvxgapkizry

# Configuraci\u00F3n de seguridad para evitar bloqueos en la nube
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Tiempos de espera (Aumentamos a 10 segundos para darle margen a Render)
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Activa el debug para ver el rastro completo en los Logs de Render
spring.mail.properties.mail.debug=true